pipeline {
  agent {
    docker { image 'maven:3.8.6-openjdk-11' }
  }
  stages {
    stage('Prepare') {
      steps {
        sh 'mkdir -p src/main/java'
        sh """
          cat <<EOF > src/main/java/HelloWorld.java
          public class HelloWorld {
            public static void main(String[] args) {
              System.out.println("Hello, World!");
            }
          }
EOF
        """
      }
    }
    stage('Compile and Run') {
      steps {
        sh 'javac src/main/java/HelloWorld.java'
        sh 'java -cp src/main/java HelloWorld'
      }
    }
  }
}
